default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  username: pguser
  password: pguser

development:
  <<: *default
  database: cdm-admin-linux_development

test:
  <<: *default
  database: cdm-admin-linux_test


production:
  <<: *default
  database: cdm-admin-linux_production
  username: cdm-admin-linux
  password: <%= ENV['CDM-ADMIN-LINUX_DATABASE_PASSWORD'] %>
