default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5

development:
  <<: *default
  username: xnvinwhyuswtpn
  password:  pG24tBHloG7cBIUnkGZ8Eyvqi2
  host: ec2-79-125-126-192.eu-west-1.compute.amazonaws.com
  port: 5432
  database: d4ndob7itmbji5

test:
  <<: *default
  database: cdm-admin_test
  username: cdm_admin
  password: '123456'

production:
  <<: *default
  username: xnvinwhyuswtpn
  password:  pG24tBHloG7cBIUnkGZ8Eyvqi2
  host: ec2-79-125-126-192.eu-west-1.compute.amazonaws.com
  port: 5432
  database: d4ndob7itmbji5
